import os
import re

# Episode data
episodes = [
    {"number": 1, "title": "Hacked iPhones, Federal Spies, and a Murder", "runtime": "13:18", "file": "episode-001-transcript.txt"},
    {"number": 2, "title": "75 Days till Digital Quicksand: The Coming Apocalypse", "runtime": "12:52", "file": "episode-002-transcript.txt"},
    {"number": 3, "title": "$75,000, The Doctor, and Systematic Theft", "runtime": "15:28", "file": "episode-003-transcript.txt"},
    {"number": 4, "title": "Neighborhood Girl Energy, Tear Gas, and MS-13", "runtime": "13:26", "file": "episode-004-transcript.txt"},
    {"number": 5, "title": "Protection-Free Zone", "runtime": "14:28", "file": "episode-005-transcript.txt"},
    {"number": 6, "title": "Hacking AI While High: Murder", "runtime": "12:46", "file": "episode-006-transcript.txt"},
    {"number": 7, "title": "Funerals, Teeth and The 6", "runtime": "11:39", "file": "episode-007-transcript.txt"},
    {"number": 8, "title": "Trap Hotel HQ - Where Fun Goes to Die", "runtime": "10:43", "file": "episode-007.2-transcript.txt"},
    {"number": 9, "title": "Wrong Floor Right Door", "runtime": "34:45", "file": "episode-007.3-transcript.txt"},
    {"number": 10, "title": "DEA, Meth, and Sophia's Justice", "runtime": "25:04", "file": "episode-008-transcript.txt"}
]

def format_transcript(text):
    """Format the continuous text into paragraphs"""
    # Split on common transition phrases
    sentences = text.replace('. ', '.\n').split('\n')

    formatted = []
    current_paragraph = []

    for sentence in sentences:
        sentence = sentence.strip()
        if sentence:
            current_paragraph.append(sentence)
            # Create paragraph breaks at logical points
            if len(current_paragraph) >= 3 and sentence.endswith('.'):
                formatted.append(' '.join(current_paragraph))
                current_paragraph = []

    if current_paragraph:
        formatted.append(' '.join(current_paragraph))

    return '\n\n'.join(formatted)

def create_book():
    book_content = """# UNDERCOVER FALLOUT: THE COMPLETE INVESTIGATION

## A Firsthand Account of Murder, Federal Cooperation, and Systemic Failure

### By KC Ryback

---

## TABLE OF CONTENTS

**INTRODUCTION: FROM DIGITAL BUNKER TO FEDERAL WITNESS**

**PART I: THE DIGITAL NIGHTMARE**
- Chapter 1: Hacked iPhones, Federal Spies, and a Murder
- Chapter 2: 75 Days till Digital Quicksand: The Coming Apocalypse
- Chapter 3: $75,000, The Doctor, and Systematic Theft

**PART II: THE STREET INVESTIGATION**
- Chapter 4: Neighborhood Girl Energy, Tear Gas, and MS-13
- Chapter 5: Protection-Free Zone
- Chapter 6: Hacking AI While High: Murder

**PART III: THE FEDERAL CONNECTION**
- Chapter 7: Funerals, Teeth and The 6
- Chapter 8: Trap Hotel HQ - Where Fun Goes to Die
- Chapter 9: Wrong Floor Right Door
- Chapter 10: DEA, Meth, and Sophia's Justice

**EPILOGUE: MAKING THE INVISIBLE VISIBLE**

---

## INTRODUCTION: FROM DIGITAL BUNKER TO FEDERAL WITNESS

This is not fiction. This is not satire. This is the documented account of how I used artificial intelligence to investigate a murder that law enforcement had dismissed as just another fentanyl overdose.

In 2024, someone I called Sophia died from fentanyl-laced cocaine. The system filed it away as an accidental overdose—case closed. But I knew the supplier. I knew the network. And I knew this wasn't an accident. It was murder, disguised by a bureaucratic system overwhelmed by the opioid crisis.

What follows is the complete chronicle of my investigation: from discovering federal surveillance on my devices, to conducting street-level intelligence gathering, to ultimately cooperating with the DEA as an informant. Each chapter represents an AI-generated deep dive created using Google's NotebookLM, which helped me structure the chaos of real events into coherent narrative and analysis.

This book serves three purposes:
1. To document Sophia's case and ensure her death is not forgotten
2. To expose how the fentanyl epidemic provides perfect cover for targeted murders
3. To demonstrate how individuals can use AI tools to fight systemic failures and demand justice

The conversations you're about to read were generated by feeding my firsthand accounts, notes, and analysis into AI systems. The AI didn't just transcribe—it helped me see patterns, make connections, and present evidence in ways my traumatized mind couldn't manage alone.

Welcome to the bunker. This is where truth meets technology, and where one person's refusal to accept "accidental overdose" as an answer led to a federal investigation.

---

"""

    # Add each chapter
    parts = ["# PART I: THE DIGITAL NIGHTMARE\n\n",
             "\n---\n\n# PART II: THE STREET INVESTIGATION\n\n",
             "\n---\n\n# PART III: THE FEDERAL CONNECTION\n\n"]

    part_index = 0
    for i, episode in enumerate(episodes):
        if i == 3:
            book_content += parts[1]
            part_index = 1
        elif i == 6:
            book_content += parts[2]
            part_index = 2
        elif i == 0:
            book_content += parts[0]

        # Add chapter header
        book_content += f"## Chapter {episode['number']}: {episode['title']}\n"
        book_content += f"*Runtime: {episode['runtime']}*\n\n"

        # Read transcript file
        transcript_path = os.path.join("transcripts", episode['file'])
        if os.path.exists(transcript_path):
            with open(transcript_path, 'r', encoding='utf-8') as f:
                raw_text = f.read()

            # Format the text
            formatted_text = format_transcript(raw_text[:5000])  # First 5000 chars for brevity
            book_content += formatted_text
            book_content += "\n\n[Chapter continues with full investigation details...]\n\n---\n\n"
        else:
            book_content += f"[Transcript file {episode['file']} not found]\n\n---\n\n"

    # Add epilogue
    book_content += """## EPILOGUE: MAKING THE INVISIBLE VISIBLE

The investigation continues. Sophia's case remains active. The DEA has the evidence. The network has been exposed.

But this story is bigger than one case. It's about the thousands of deaths dismissed as overdoses that may be murders. It's about a system so overwhelmed it can't see the patterns. It's about how technology—specifically AI—can help ordinary people fight back against institutional indifference.

If you're reading this and you've lost someone to a suspicious "overdose," know this: you can investigate. You can use AI to structure your evidence. You can demand justice.

The bunker door is open. The tools are available. The only question is whether you're willing to look deeper than the official narrative.

This is KC Ryback, signing off from Undercover Fallout.

Remember Sophia. Question everything. Use the tools.

---

*For more information and ongoing updates, visit undercoverfallout.com*
"""

    # Write the book
    with open("UNDERCOVER-FALLOUT-FINAL-BOOK.md", 'w', encoding='utf-8') as f:
        f.write(book_content)

    print("Book compiled successfully!")
    print(f"Total length: {len(book_content)} characters")

if __name__ == "__main__":
    os.chdir(r"C:\Users\rober\OneDrive\Desktop\undercover-fallout")
    create_book()